### ISSUE TITLE
Hi is this support Migration?

### ISSUE THREAD

**Issue by a121984376** [denis-ivanov/EntityFrameworkCore.ClickHouse#14]
I use like this
![image](https://user-images.githubusercontent.com/15758574/145786897-b6211860-7aeb-4ff6-bee7-9f0113c400d4.png)

![image](https://user-images.githubusercontent.com/15758574/145786867-ebc1de17-17a0-45f1-81e1-6f8c01a2569f.png)

**Comment by a121984376** [comment]
![image](https://user-images.githubusercontent.com/15758574/145786991-7b9f5034-1718-4995-93a2-aba135b28d0d.png)

**Comment by denis-ivanov** [comment]
Hi, @a121984376!
It's not done yet.

**Comment by a121984376** [comment]
do you  have plan to support Migrations?

**Comment by denis-ivanov** [comment]
@a121984376, yes, I have plans, but no time.
