### ISSUE TITLE
The instance of entity type 'AnswerSheet' cannot be tracked because another instance with the same key value for {'SheetId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

### ISSUE THREAD

**Issue by qiqistart** [denis-ivanov/EntityFrameworkCore.ClickHouse#18]
halo  ,author ，Update Data report an error:The instance of entity type 'AnswerSheet' cannot be tracked because another instance with the same key value for {'SheetId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

**Comment by denis-ivanov** [comment]
Please, try a new version [EntityFrameworkCore.ClickHouse/0.0.12](https://www.nuget.org/packages/EntityFrameworkCore.ClickHouse/0.0.12) and if it's still reproducible provide a minimum working example.
