### ISSUE TITLE
Scaffold have problems

### ISSUE THREAD

**Issue by Hedkeaf** [denis-ivanov/EntityFrameworkCore.ClickHouse#19]
When i do scaffold from manager-console i have an error:
Unable to find expected assembly attribute [DesignTimeProviderServices] in provider assembly 'EntityFrameworkCore.ClickHouse'. This attribute is required to identify the class which acts as the design-time service provider factory for the provider.
Maybe i do something wrong? Could u add some "GetStart" or any basic documentation for usage? Thank you for attention.

**Comment by denis-ivanov** [comment]
Please, try a new version [EntityFrameworkCore.ClickHouse/0.0.12](https://www.nuget.org/packages/EntityFrameworkCore.ClickHouse/0.0.12) and if it's still reproducible provide a minimum working example.

**Comment by denis-ivanov** [comment]
@Hedkeaf, scaffolding now should work. If it's still reproducible, please open a new issue with full information: db schema, command line, version of package.
