### ISSUE TITLE
not support Round(1,2)

### ISSUE THREAD

**Issue by ysq5202121** [denis-ivanov/EntityFrameworkCore.ClickHouse#24]
not support Math.Round(a.Sum(),2)

**Comment by ysq5202121** [comment]
if (RoundDouble.Equals(method) || RoundDecimal.Equals(method))
            {
                return _sqlExpressionFactory.Function(
                    name: "Round",
                    arguments: arguments,
                    nullable: false,
                    argumentsPropagateNullability: new[] { true },
                    returnType: method.ReturnType);
            }

**Comment by ysq5202121** [comment]
private static readonly MethodInfo RoundDecimal1 = typeof(Math)
        .GetRuntimeMethod(nameof(Math.Round), new[] { typeof(decimal), typeof(Int32) });

It should be possible to have multiple parameters

**Comment by ysq5202121** [comment]
private static readonly MethodInfo RoundDecimal1 = typeof(Math)
        .GetRuntimeMethod(nameof(Math.Round), new[] { typeof(decimal), typeof(Int32) });
The above can support rounding @denis-ivanov

**Comment by denis-ivanov** [comment]
https://www.nuget.org/packages/EntityFrameworkCore.ClickHouse/0.0.10
