### ISSUE TITLE
Count is not working

### ISSUE THREAD

**Issue by georgeemr** [denis-ivanov/EntityFrameworkCore.ClickHouse#31]
When you call Count, the next exception is thrown.

![image](https://github.com/denis-ivanov/EntityFrameworkCore.ClickHouse/assets/3822009/72fd9fe1-b94a-41a8-8e5c-b1aefbe3f49c)

The table have more than 5 million records.

Tested on 0.0.13.

Appreciate your help.

**Comment by denis-ivanov** [comment]
Hi, @georgeemr !

Please, provide full example, with entities and db schema.

**Comment by Eflarus** [comment]
I had the same problem
You can use typecast `(Int64)` to fix it like here
```csharp
var query =
  from MyModel mm in _context.MyModels
  group mm by mm.Name into g
  select new { g.Key, Likes = (Int64)g.Sum(o => o.Likes) };
```
