### ISSUE TITLE
Can translate, clickhouse cannot execute

### ISSUE THREAD

**Issue by ysq5202121** [denis-ivanov/EntityFrameworkCore.ClickHouse#32]
```sql
SELECT "t"."Sku", "t"."StockRegionCode", "t"."ShipmentDate0", COALESCE(SUM("t"."SalesQty"), 0), COALESCE(SUM("t"."NetSalesPrice" * "t"."ExchangeRate"), 0.0), COALESCE(SUM("t"."NetSalesPrice" * "t"."ExchangeRate"), 0.0) / CAST(COALESCE(SUM("t"."SalesQty"), 0) AS Decimal(32, 9))
FROM (
    SELECT "g"."NetSalesPrice", "g"."SalesQty", "g"."Sku", "s"."StockRegionCode", "o"."ExchangeRate", "toYYYYMM"("g"."ShipmentDate") AS "ShipmentDate0"
    FROM "GP_Order_View" AS "g"
    LEFT JOIN "Site" AS "s" ON "g"."SiteID" = "s"."SiteID"
    LEFT JOIN "ODS_Base_CurrencyMonth" AS "o" ON "g"."Period" = "o"."DayPeriod" AND "g"."Currency" = "o"."CurrencyName"
    WHERE "g"."OrderTypeID" = 10 AND "g"."SourceTalbe" = 'GP_OrderDetail' AND "g"."ShipmentDate" >= '2024-04-01' AND "g"."ShipmentDate" < '2024-04-30'
) AS "t"
GROUP BY "t"."Sku", "t"."StockRegionCode", "t"."ShipmentDate0"
```

The outer layer cannot access the inner layer, and "As" needs to be added inside. I'm not sure if there is a good solution
Nested syntax is prone to this problem and is quite common

Error
 [47] [07000]: Code: 47. DB::Exception: There's no column 't.Sku' in table 't': While processing t.Sku. (UNKNOWN_IDENTIFIER) (version 23.6.2.18 (official build))

**Comment by ysq5202121** [comment]
@denis-ivanov expect a reply

**Comment by denis-ivanov** [comment]
@ysq5202121, provide full example with db schema, LINQ models, etc.

**Comment by ysq5202121** [comment]
var List = (from d in OrderQuery
             join s in SiteQuery on d.SiteID equals s.SiteID into ds
             from s in ds.DefaultIfEmpty()
             join c in CurrencyQuery on new { d.Period, d.Currency }
             equals new { Period = c.DayPeriod, Currency = c.CurrencyName } into dc
             from c in dc.DefaultIfEmpty()
             where d.OrderTypeID == 10 && d.SourceTalbe == "GP_OrderDetail" && d.ShipmentDate >= StartDate && d.ShipmentDate < EndDate
             group new { d, s, c } by new { d.Sku, s.StockRegionCode, ShipmentDate = ClickQueryFunctions.toYYYYMM(d.ShipmentDate) }
             into g
             select new SkuMonthSalesByShipmentDate()
             {
                 Sku = g.Key.Sku,
                 StockRegionCode = g.Key.StockRegionCode,
                 Period = g.Key.ShipmentDate.ToString(),
                 TotalSalesQty = g.Sum(x => x.d.SalesQty),
                 TotalSalesAmt = g.Sum(x => x.d.NetSalesPrice * x.c.ExchangeRate),
                 AvgSalesPrice = g.Sum(x => x.d.NetSalesPrice * x.c.ExchangeRate) / g.Sum(x => x.d.SalesQty)
             }).ToList();

![image](https://github.com/denis-ivanov/EntityFrameworkCore.ClickHouse/assets/8586973/b6e60865-f912-4a5f-be7f-79c54dbf2769)
If you don't add custom functions, you won't be able to generate subqueries
More examples can be provided
@denis-ivanov

**Comment by denis-ivanov** [comment]
@ysq5202121, I don't see db schema and models.

**Comment by ysq5202121** [comment]
clickhouse :23.6.2.18
` /// <summary>
 /// 订单预报
 /// </summary>
 [Table("GP_Order_View")]
 [Comment("订单预报")]
 public class GP_Order_View : IEntity<ClickHouseDBContextLocator>, IEntity<MasterDbContextLocator>, IEntityTypeBuilder<GP_Order_View>
 {

     public void Configure(EntityTypeBuilder<GP_Order_View> entityBuilder, DbContext dbContext, Type dbContextLocator)
     {
         entityBuilder.HasKey(u => u.Id);
     }

     /// <summary>
     /// Id
     /// </summary>
     [SugarColumn(IsPrimaryKey = true, IsIdentity = true)]//数据库是自增才配自增
     [Key, Column(Order = 1)]
     public Int32 Id { get; set; }

     /// <summary>
     /// 期间
     /// </summary>
     public String Period { get; set; }

     /// <summary>
     /// 结算时间
     /// </summary> 
     public DateTime SettlementTime { get; set; }

     /// <summary>
     /// 订单明细ID
     /// </summary>
     public Int32 OrderDetailId { get; set; }

     /// <summary>
     /// 实际销售金额
     /// </summary>
     public Decimal NetSalesPrice { get; set; }

     /// <summary>
     /// 采购成本
     /// </summary>
     public Decimal PurchaseAmt { get; set; }

     /// <summary>
     /// 头程成本
     /// </summary>
     public Decimal FirstShipAmt { get; set; }

     /// <summary>
     /// 退款金额
     /// </summary>
     public Decimal RefundAmt { get; set; }

     /// <summary>
     /// 运费金额预估
     /// </summary>
     public Decimal ShipAmtCalc { get; set; }

     /// <summary>
     /// 运费金额实际
     /// </summary>
     public Decimal ShipAmtActual { get; set; }

     /// <summary>
     /// 手续费预估
     /// </summary>
     public Decimal CommissionAmtCalc { get; set; }

     /// <summary>
     /// 手续费实际
     /// </summary>
     public Decimal CommissionAmtActual { get; set; }

     /// <summary>
     /// 税金
     /// </summary>
     public Decimal TaxAmt { get; set; }

     /// <summary>
     /// 币种
     /// </summary>
     public String Currency { get; set; }

     /// <summary>
     /// 免邮
     /// </summary>
     public bool IsFreeShip { get; set; }

     /// <summary>
     /// 免交易费
     /// </summary>
     public bool IsFreeCommission { get; set; }
    
     /// <summary>
     /// 运费金额
     /// </summary>
     public Decimal ShipAmt { get; set; }

     /// <summary>
     /// 退款手续费
     /// </summary>
     public Decimal ReufndComission { get; set; }

     /// <summary>
     /// 手续费
     /// </summary>
     public Decimal CommissionAmt { get; set; }

     /// <summary>
     /// 实际销售金额(计提)
     /// </summary>
     public Decimal FsNetSalesPrice { get; set; }

     /// <summary>
     ///折扣金额(计提)
     /// </summary>
     public Decimal FsDiscountPrice { get; set; }

     /// <summary>
     ///线上运费(计提)
     /// </summary>
     public Decimal FSOnLineShipAmt { get; set; }

     /// <summary>
     ///手续费(计提)
     /// </summary>
     public Decimal FsCommissionAmt { get; set; }

     /// <summary>
     ///线下运费(计提)
     /// </summary>
     public Decimal FsOffLineShipAmt { get; set; }

     /// <summary>
     ///销售金额(计提)
     /// </summary>
     public Decimal FsSalesPrice { get; set; }

     /// <summary>
     ///TempOrderInfoID
     /// </summary>
     public Int32 TempOrderInfoID { get; set; }

     /// <summary>
     ///OrderInfoID
     /// </summary>
     public Int32 OrderInfoID { get; set; }

     /// <summary>
     /// 账号
     /// </summary>
     public Int32 AccountId { get; set; }

     /// <summary>
     /// 平台
     /// </summary>
     public Int32 SalesPlatformID { get; set; }

     /// <summary>
     /// 站点
     /// </summary>
     public Int32 SiteID { get; set; }

     /// <summary>
     /// OrderNo
     /// </summary>
     public String OrderNo { get; set; }

     /// <summary>
     /// SellerSku
     /// </summary>
     public String SellerSku { get; set; }

     /// <summary>
     /// ItemId
     /// </summary>
     public String ItemId { get; set; }

     /// <summary>
     /// 在线对应ED Sku
     /// </summary>
     public String ItemEDSku { get; set; }

     /// <summary>
     /// Sku
     /// </summary>
     public String Sku { get; set; }

     /// <summary>
     /// FnSku
     /// </summary>
     public String FnSku { get; set; }

     /// <summary>
     /// 销售金额
     /// </summary>
     public Decimal SalesPrice { get; set; }

     /// <summary>
     /// 折扣金额
     /// </summary>
     public Decimal DiscountPrice { get; set; }

     /// <summary>
     /// 销售数量
     /// </summary>
     public Int32 SalesQty { get; set; }

     /// <summary>
     /// 销售数量
     /// </summary>
     public string SalesCurrnecy { get; set; }

     /// <summary>
     /// 下单时间
     /// </summary>
     public DateTime PostOrderDate { get; set; }

     /// <summary>
     /// 付款时间
     /// </summary>
     public DateTime PaymentDate { get; set; }

     /// <summary>
     /// 发货时间
     /// </summary>
     public DateTime ShipmentDate { get; set; }

     /// <summary>
     /// 发货渠道
     /// </summary>
     public string FulfillmentChannel { get; set; }

     /// <summary>
     /// 发货仓库ID
     /// </summary>
     public int ShipStoreHouseID { get; set; }

     /// <summary>
     /// IsFBA
     /// </summary>
     public bool IsFBA { get; set; }

     /// <summary>
     /// 订单类型Id
     /// </summary>
     public int OrderTypeID { get; set; }

     /// <summary>
     /// 备注
     /// </summary>
     public String Remart { get; set; } = "";

     /// <summary>
     /// 是否虚拟订单
     /// </summary>
     public bool IsVirtualOrder { get; set; }

     /// <summary>
     /// 原始销售数量(AukeysOrder..TempOrderInfo.Quantity)
     /// </summary>
     public int OriginalSalesQty { get; set; }

     /// <summary>
     /// 目的国家
     /// </summary>
     public string ShipToCountry { get; set; }

     /// <summary>
     /// 发货方式
     /// </summary>
     public int PackageTypeID { get; set; }

     /// <summary>
     /// OrderInfo.rowversion
     /// </summary>
     public int RVInt { get; set; }

     /// <summary>
     /// 付款方式编码
     /// </summary>
     public int PaymentMethodCode { get; set; }

     /// <summary>
     /// 订单状态
     /// </summary>
     public int OrderStatus { get; set; }

     /// <summary>
     /// 是否捆绑Id
     /// </summary>
     public bool IsBundlingOrder { get; set; }

     /// <summary>
     /// 商品编码
     /// </summary>
     public string Code { get; set; }

     /// <summary>
     /// 核销期间
     /// </summary>
     public string VerificationPeriod { get; set; }

     /// <summary>
     /// 是否已经月结
     /// </summary>
     public bool IsMonthSettlement { get; set; }

     /// <summary>
     /// 外键：月结Id
     /// </summary>
     public int MonthSettlementId { get; set; }

     /// <summary>
     /// 订单交易ID
     /// </summary>
     public string TransactionID { get; set; }

     /// <summary>
     /// MultiChannelOrderType
     /// </summary>
     public string MultiChannelOrderType { get; set; }

     /// <summary>
     /// ItemName
     /// </summary>
     public string ItemName { get; set; }

     /// <summary>
     /// CreatorUser
     /// </summary>
     public string CreatorUser { get; set; }

     /// <summary>
     /// 修改人
     /// </summary>
     public string UpdateUser { get; set; }

     /// <summary>
     /// 创建时间
     /// </summary>
     public DateTime CreateTime { get; set; }

     /// <summary>
     /// 更新时间
     /// </summary>
     public DateTime UpdateTime { get; set; }

     /// <summary>
     /// 原表
     /// </summary>
     public string SourceTalbe { get; set; }

 }`
If necessary, I can write a dome, which is a common problem

**Comment by denis-ivanov** [comment]
https://en.wikipedia.org/wiki/Minimal_reproducible_example

`ClickHouseDBContextLocator`, `MasterDbContextLocator`, etc - what is it?

**Comment by ysq5202121** [comment]
[ClickHouseTest.zip](https://github.com/denis-ivanov/EntityFrameworkCore.ClickHouse/files/15247587/ClickHouseTest.zip)
@denis-ivanov Dome

**Comment by ysq5202121** [comment]
@denis-ivanov

**Comment by denis-ivanov** [comment]
@ysq5202121, minimal working example is not Zip file.
