### ISSUE TITLE
(Question) Support for MATERIALIZED and/or ALIAS?

### ISSUE THREAD

**Issue by TPCharts** [denis-ivanov/EntityFrameworkCore.ClickHouse#52]
I'm considering using MATERIALIZED and/or ALIAS columns, if available.

Does this library currently support these, or anything similar?

Entity Framework computed columns: https://learn.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#computed-columns

ClickHouse Materialized columns: https://clickhouse.com/docs/en/sql-reference/statements/create/table#materialized

ClickHouse Alias columns: https://clickhouse.com/docs/en/sql-reference/statements/create/table#alias

**Comment by denis-ivanov** [comment]
https://github.com/denis-ivanov/EntityFrameworkCore.ClickHouse/blob/master/EntityFrameworkCore.ClickHouse/Migrations/ClickHouseMigrationsSqlGenerator.cs#L21

Yes, it does
